language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'
- bash .travis/push.sh
env:
  global:
    secure: PELuQmrYmOeKY9nCNVrLXW0inYsgNBtc99PryjL1l9c9Anyip+f/2/KpRCv1UVH6zrdZz8dhC8n1l9OQYYKQoQV/R4HKCKUcYfNydggq/O1RSA+ai3PgqkgZDczw5ZnwlEMF961qtQ2JBtyNuwd+XLtX5v80EYrZ7iDaWiJW9ry3jeaZJm5egh+T7n9tyoLRiABw4DfjIW3dWM5ombd49PzMOcQ8Gl/wjEvUxaumMTc6HPIi3areiAtsmRMLpEE32Xb7ur5po5Fmg10gnJrZvAB0EzLqHmo1DLm9D4Y46rTmW8Jh2aFhh9RYWvI1I2FKhOHLNwjwHnyZkenhD9F5uoQe+eltH5/4RHq898jOKanaTNWT/47bsbh4eiJcAVXcZjffn/0HryYPMIL5DNiMlZIJVHpXMaIteZhWHjmUtfgY2Sd61/9ib9+Mp32wwdxRzQAZwfHk9XnwEePQwD1v9zrXU6utBf8eaNLzbucS6KIpR7eILek/XNzycShRTdqmLG/w+CkFq+efkORVRB5ga/ZKBAg6XUV+y0iM7RG2+zmoFMEoiY5Bewc0BXPCFbgJGd8exLSFx928eEYLW1TnKA7n+p2mIynBObCRk4Jm+XtrCKd3MJD4k3ADsOLA6Qj+hVKL/FJuJ2WZsRBK1LoE/M5e9ma6tKb3twAKOkTvspk=
