language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'
- bash .travis/push.sh
env:
  global:
    secure: A1s63RlflXv1j+J9gaN+lQCdWyuQttQfMPzXcw4mSe93D4kdot8x5ensYKoqWJx2LqyHWvJx6En4qbyX0XmFhI+vyGkB4w7TJO6X/fai7LoBy8MwqoR5lTsw2/5XE0f0g9C9dVhjQijjsJ+3kTD/c+FMtI8exO9SF8BTwKrd3vhqZbC8LlpJT/vmOqbojwvuvhgpFyP/wNgFsXwDGmOOk4D7asUX11ENmXos4zralJ+fMiWR9PwOp0bSzGkv9WjuE/8iha0P1ehsk2OlQJSMB8VuPVs48Wjdzkq31voZc7+P2mHWvUzJV3gX5wx/kTt6zeYKVczAGen+aBW6P0Q3BPmjXphUWWeaq7qV2PRQUBOlaaHef/7YTbNfoWT1kd9nJNnwedDRv7P84P3l+Q0ErParm0vSwgJ6Vcrm8ElHqWPQ9VhJ4z9hxHhcsdaehNIbyoCVkmas+TjWJmOtgDCl32XOd5D7Ursqped0v8HIJLE1mzB7WkyfdVq4Kjl/oBGgf/46rPB/Z2wLg5NiK1TwhOiiYf0RVQNtypAj7rSeMy95kv9ak+rOYM28aps940qqob9G/f6zrqwLS+EAWB+QeMs7AZdnPmGWkF/ldYrr0njCcHLJw2wbGcQMfT2tpzbRxeIk9dXFk0awZ8DUwiiUcCITqVZDNVhRgSxEtq1b3m4=
