language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'
- bash .travis/push.sh
env:
  global:
    secure: N0g1AxszZyGmMJ2HuzUY8J0+6bk1fcZ33NSAocu6UUZ/JT27vrDr45jJFzrMOGTIvoBxBzdAU0ljKuKx0KH+hAgAVyQ3xmmr8dbRP9RV+hS9eYHAf7jQm/kc1/lg87s0my2gobuVCh8G9QJ8Lv8J3qkJ8jQh8H4U2SJfA06a0jrJ4QP3MZHrMcNzO30/kaTOaHvW65PcRBhEd+bNbUB+oArERXwRer0knqhvDSMCs8KeTZ9FUWFWjJj9AAOFNToupasFU412IOg9CH6R56sKuxmujGx4UkQOK9PWBek5+2FRitqeWnshTTMVp2A4ky0SQXuQfaGYoVSyTiFt44cLO+G43ZXzZnA6N2bjExcujl9M7MabSQRTiVP1315/MRI9YayFrkJBR7J02Y03rLrsTmcA/rEYyyIQIFNH0XmAuc2QMv8Y0EnBo8NDJ2PrFbzGmxRStT2Q4l0scC25aUEOPcnwbXKe1bnFI0Y/Wk+qjsfIOg1nF6282pzQY4J+NH/ctVxCEDoY4UQ1Uq8r+4lL57/isIy1lEi0aplnIC+IPnixjxf7vTW+FL2XltRj+7KMaKhwYcNwhsb1F6aeofFg00WlnbCEVfeMCsiROkeXzORrH1wnx2bLdcl9yD0e1ovASNhVfWerrVCcojG6nmxb/xZWCkL3XIoJc9cRT8wtGsA=
